HOSTS:
  teamcity.test:
    roles:
      - master
      - agent
    platform: el-6-x86_64
    box : centos-65-x64-virtualbox-nocm
    box_url : http://puppet-vagrant-boxes.puppetlabs.com/centos-65-x64-virtualbox-nocm.box
    hypervisor : vagrant
    ip         : 10.0.2.15
CONFIG:
    log_level: verbose
    type: git
    vagrant_memsize: 4096